//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proje
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullanicilar
    {
        public int id { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public Nullable<double> Puan { get; set; }
        public string Soru1 { get; set; }
        public string Soru2 { get; set; }
        public string Soru3 { get; set; }
        public string Soru4 { get; set; }
        public string Soru5 { get; set; }
        public string Soru6 { get; set; }
        public string Soru7 { get; set; }
        public Nullable<int> Boy { get; set; }
        public Nullable<int> Kilo { get; set; }
        public Nullable<int> Yas { get; set; }
    }
}
